version: "3.9"

services:
  # ---------------- DBs ----------------
  postgres-users:
    image: postgres:16
    container_name: postgres-users
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    networks:
      - qa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d users_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  postgres-auth:
    image: postgres:16
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5440:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - qa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  postgres-inventory:
    image: postgres:16
    container_name: postgres-inventory
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_inventory_data:/var/lib/postgresql/data
    networks:
      - qa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventory_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - qa-network

  mongo-notifications:
    image: mongo:7
    container_name: mongo-notifications
    ports:
      - "27017:27017"
    volumes:
      - mongo_notifications_data:/data/db
    networks:
      - qa-network

  # ---------------- Core services ----------------
  api-users:
    build: ./apps/api-users
    container_name: api-users
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - GLOBAL_PREFIX=api/v1
      - DATABASE_URL=postgresql://postgres:postgres@postgres-users:5432/users_db?schema=public
      - INTERNAL_TOKEN=super-internal-123
    depends_on:
      postgres-users:
        condition: service_healthy
    networks:
      - qa-network

  api-auth:
    build:
      context: .
      dockerfile: apps/api-auth/Dockerfile
    container_name: api-auth
    env_file:
      - apps/api-auth/.env
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - GLOBAL_PREFIX=api/v1
      - JWT_SECRET=qa_secret
      - DATABASE_URL=postgresql://postgres:postgres@postgres-auth:5432/auth_db?schema=public
      - USERS_SERVICE_URL=http://api-users:3001/api/v1
      - INTERNAL_TOKEN=super-internal-123
      - REDIS_URL=redis://redis-cache:6379
    depends_on:
      postgres-auth:
        condition: service_healthy
      api-users:
        condition: service_started
      redis-cache:
        condition: service_started
    networks:
      - qa-network

  api-inventory:
    build: ./apps/api-inventory
    container_name: api-inventory
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - GLOBAL_PREFIX=api/v1
      - DATABASE_URL=postgresql://postgres:postgres@postgres-inventory:5432/inventory_db?schema=public
    depends_on:
      postgres-inventory:
        condition: service_healthy
    networks:
      - qa-network
    command: >
      sh -c "npx prisma migrate deploy || true; node dist/main.js"

  # ---------------- Other services (por ahora) ----------------
  api-loans:
    build: ./apps/api-loans
    container_name: api-loans
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - GLOBAL_PREFIX=api/v1
      - REDIS_URL=redis://redis-cache:6379
    depends_on:
      redis-cache:
        condition: service_started
    networks:
      - qa-network

  api-reservations:
    build: ./apps/api-reservations
    container_name: api-reservations
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - GLOBAL_PREFIX=api/v1
      - REDIS_URL=redis://redis-cache:6379
    depends_on:
      redis-cache:
        condition: service_started
    networks:
      - qa-network

  api-notifications:
    build: ./apps/api-notifications
    container_name: api-notifications
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - GLOBAL_PREFIX=api/v1
      - MONGO_URL=mongodb://mongo-notifications:27017/notifications_db
    depends_on:
      mongo-notifications:
        condition: service_started
    networks:
      - qa-network

  api-audit:
    build: ./apps/api-audit
    container_name: api-audit
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
      - GLOBAL_PREFIX=api/v1
      - MONGO_URL=mongodb://mongo-notifications:27017/audit_db
    depends_on:
      mongo-notifications:
        condition: service_started
    networks:
      - qa-network

  api-reports:
    build: ./apps/api-reports
    container_name: api-reports
    ports:
      - "3007:3007"
    environment:
      - PORT=3007
      - GLOBAL_PREFIX=api/v1
    networks:
      - qa-network

  api-automation:
    build: ./apps/api-automation
    container_name: api-automation
    ports:
      - "3008:3008"
    environment:
      - PORT=3008
      - GLOBAL_PREFIX=api/v1
    networks:
      - qa-network

  api-integration:
    build: ./apps/api-integration
    container_name: api-integration
    ports:
      - "3009:3009"
    environment:
      - PORT=3009
      - GLOBAL_PREFIX=api/v1
    networks:
      - qa-network

networks:
  qa-network:
    driver: bridge

volumes:
  postgres_users_data:
  postgres_auth_data:
  postgres_inventory_data:
  mongo_notifications_data:
