export const ENV = {
  AUTH: process.env.NEXT_PUBLIC_API_AUTH!,
  USERS: process.env.NEXT_PUBLIC_API_USERS!,
  INVENTORY: process.env.NEXT_PUBLIC_API_INVENTORY!,
  LOANS: process.env.NEXT_PUBLIC_API_LOANS!,
  RESERVATIONS: process.env.NEXT_PUBLIC_API_RESERVATIONS!,
  REPORTS: process.env.NEXT_PUBLIC_API_REPORTS!,
  AUTOMATION: process.env.NEXT_PUBLIC_API_AUTOMATION!,
  INTEGRATION: process.env.NEXT_PUBLIC_API_INTEGRATION!,
  KAFKA_UI: process.env.NEXT_PUBLIC_KAFKA_UI!,
};
