services:
  # ---------------- Kafka (Redpanda) ----------------
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "1G"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
      - "9644:9644"
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: redpanda:9092
    depends_on:
      - redpanda
    restart: unless-stopped

  # ---------------- DBs ----------------
  postgres-users:
    image: postgres:16
    container_name: postgres-users
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports: ["5433:5432"]
    volumes: [postgres_users_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d users_db"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  postgres-auth:
    image: postgres:16
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports: ["5440:5432"]
    volumes: [postgres_auth_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  postgres-inventory:
    image: postgres:16
    container_name: postgres-inventory
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    ports: ["5435:5432"]
    volumes: [postgres_inventory_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventory_db"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  postgres-loans:
    image: postgres:16
    container_name: postgres-loans
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loans_db
    ports: ["5436:5432"]
    volumes: [postgres_loans_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d loans_db"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  postgres-reservations:
    image: postgres:16
    container_name: postgres-reservations
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservations_db
    ports: ["5437:5432"]
    volumes: [postgres_reservations_data:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reservations_db"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    ports: ["6379:6379"]
    restart: unless-stopped

  mongo-audit:
    image: mongo:7
    container_name: mongo-audit
    ports: ["27017:27017"]
    volumes: [mongo_audit_data:/data/db]
    restart: unless-stopped

volumes:
  redpanda_data:
  postgres_users_data:
  postgres_auth_data:
  postgres_inventory_data:
  postgres_loans_data:
  postgres_reservations_data:
  mongo_audit_data:
